name 'dcae-ci-tests'
maintainer 'Avishai G'
maintainer_email 'ag860a@intl.att.com'
license 'all_rights'
description 'Installs/Configures dcae-ci-tests'
long_description 'Installs/Configures DCAE-CI'
version '1.0.0'
