/*-
 * ============LICENSE_START=======================================================
 * SDC
 * ================================================================================
 * Copyright (C) 2017 - 2019 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

package org.onap.dcae.ci.api.tests.blueprint;

import com.aventstack.extentreports.Status;
import org.onap.dcae.ci.api.tests.DcaeRestBaseTest;
import org.onap.dcae.ci.entities.RestResponse;
import org.onap.dcae.ci.report.Report;
import org.onap.dcae.ci.utilities.DcaeRestClient;
import org.onap.sdc.dcae.composition.restmodels.health.HealthResponse;
import org.testng.annotations.Test;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;

public class ToscaLabApiTests extends DcaeRestBaseTest {

	private String validInput = "{\"template\":\"dG9wb2xvZ3lfdGVtcGxhdGU6CiAgbm9kZV90ZW1wbGF0ZXM6CiAgICBzdXAuc3VwcGxlbWVudF9uLjE1MjU3ODE5NzY1MDAuODoKICAgICAgcmVxdWlyZW1lbnRzOgogICAgICAtIHN0cmVhbV9wdWJsaXNoXzA6IHtjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGll"
			+ "cy5zdHJlYW0uc3Vic2NyaWJlLCByZWxhdGlvbnNoaXA6IGRjYWUucmVsYXRpb25zaGlwcy5yZXdvcmtfY29ubmVjdGVkX3RvfQogICAgICAtIGhvc3Q6IHtjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5jZGFwSG9zdCwgcmVsYXRpb25zaGlwOiBkY2FlLnJlbGF0aW9uc2hpcHMuY29tcG9uZW50X2Nvb"
			+ "nRhaW5lZF9pbn0KICAgICAgLSBkZXBlbmRlbmN5OiB7Y2FwYWJpbGl0eTogdG9zY2EuY2FwYWJpbGl0aWVzLk5vZGUsIHJlbGF0aW9uc2hpcDogdG9zY2EucmVsYXRpb25zaGlwcy5EZXBlbmRzT259CiAgICAgIGNhcGFiaWxpdGllczoKICAgICAgICBzdHJlYW1fc3Vic2NyaWJlXzA6CiAgICAgICAgICBwcm"
			+ "9wZXJ0aWVzOiB7cm91dGU6IElHTk9SRSwgZm9ybWF0OiBWRVNfc3BlY2lmaWNhdGlvbiwgdmVyc2lvbjogNS4yOC40fQogICAgICBkZXNjcmlwdGlvbjogL3NkYy92MS9jYXRhbG9nL3Jlc291cmNlcy81YzFiY2FlMC1lMWQxLTRiNTMtOWVkMS1kNzI1N2UzYWVhYWIvYXJ0aWZhY3RzL2ZiZGFjYjhhLWViYzMt"
			+ "NGEyZC04Nzg3LTM2MWI5YWI1NzQyMwogICAgICB0eXBlOiB0b3NjYS5kY2FlLm5vZGVzLmNkYXBBcHAuc3VwcGxlbWVudAogICAgICBwcm9wZXJ0aWVzOgogICAgICAgIGNvbm5lY3RlZF9icm9rZXJfZG5zX25hbWU6IHtnZXRfaW5wdXQ6IGNvbm5lY3RlZF9icm9rZXJfZG5zX25hbWV9CiAgICAgICAgcGhhc2"
			+ "VzLnN1cHBsZW1lbnQucGhhc2VOYW1lOiBzdXBwbGVtZW50CiAgICAgICAgcGhhc2VzLnZlc19zdXBwbGVtZW50LnBoYXNlTmFtZTogdmVzX3N1cHBsZW1lbnQKICAgICAgICBqc29uOiAneyJwcm9jZXNzaW5nIjpbeyJwaGFzZSI6InN1cHBsZW1lbnQiLCJmaWx0ZXIiOnsiY2xhc3MiOiJPbmVPZiIsImZpZWx"
			+ "kIjoiZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuZXZlbnRUeXBlIiwidmFsdWVzIjpbInZQQ1JGX0FsYXJtcyIsInZNb0dfQWxhcm1zIiwiYXBwbGljYXRpb25WbmYiLCJHdWVzdE9TX0FsYXJtcyIsIkNvbnRyb2wiXX0sInByb2Nlc3NvcnMiOlt7ImNsYXNzIjoiTG9nVGV4dCIsImxvZ0xldmVsIjoiSU5GTyIs"
			+ "ImxvZ1RleHQiOiJFbnRlcmluZwogICAgICAgICAgc3VwcGxlbWVudCBQaGFzZSAtIEZJTFRFUiBwYXJhbWV0ZXIgIC0gJHtldmVudC5jb21tb25FdmVudEhlYWRlci5ldmVudFR5cGV9In0seyJjbGFzcyI6IkRhdGVGb3JtYXR0ZXIiLCJ2YWx1ZSI6IiR7ZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuc3RhcnRFc"
			+ "G9jaE1pY3Jvc2VjfSIsImZyb21Gb3JtYXQiOiIjbXMiLCJmcm9tVHoiOiJHTVQiLCJ0b0ZpZWxkIjoiZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuaW50ZXJuYWxIZWFkZXJGaWVsZHMuZmlyc3REYXRldGltZSIsInRvRm9ybWF0IjoiRUVFLAogICAgICAgICAgZGQgTU0geXl5eSBISDptbTpzcyB6enoiLCJ0b"
			+ "1R6IjoiR01UIn0seyJjbGFzcyI6IkRhdGVGb3JtYXR0ZXIiLCJ2YWx1ZSI6IiR7ZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIubGFzdEVwb2NoTWljcm9zZWN9IiwiZnJvbUZvcm1hdCI6IiNtcyIsImZyb21UeiI6IkdNVCIsInRvRmllbGQiOiJldmVudC5jb21tb25FdmVudEhlYWRlci5pbnRlcm5hbEhlYWRlc"
			+ "kZpZWxkcy5sYXN0RGF0ZXRpbWUiLCJ0b0Zvcm1hdCI6IkVFRSwKICAgICAgICAgIGRkIE1NIHl5eXkgSEg6bW06c3Mgenp6IiwidG9UeiI6IkdNVCJ9LHsiY2xhc3MiOiJEYXRlRm9ybWF0dGVyIiwidmFsdWUiOiIle25vdy5tc30iLCJmcm9tRm9ybWF0IjoiI21zIiwiZnJvbVR6IjoiR01UIiwidG9GaWVsZ"
			+ "CI6ImV2ZW50LmNvbW1vbkV2ZW50SGVhZGVyLmludGVybmFsSGVhZGVyRmllbGRzLmNvbGxlY3RvclRpbWVTdGFtcCIsInRvRm9ybWF0IjoiRUVFLAogICAgICAgICAgZGQgTU0geXl5eSBISDptbTpzcyB6enoiLCJ0b1R6IjoiR01UIn0seyJjbGFzcyI6IlNldCIsInVwZGF0ZXMiOnsiZXZlbnQuY29tbW9uRX"
			+ "ZlbnRIZWFkZXIuaW50ZXJuYWxIZWFkZXJGaWVsZHMuaW50ZXJuYWxIZWFkZXJGaWVsZHNWZXJzaW9uIjoiOS45IiwiZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuaW50ZXJuYWxIZWFkZXJGaWVsZHMuZXZlbnRUYWciOiIke2hwLnRhZ30ifX1dfSx7InBoYXNlIjoic3VwcGxlbWVudCIsInByb2Nlc3NvcnMiOlt7"
			+ "ImNsYXNzIjoiTG9nRXZlbnRQcmV0dHkiLCJ0aXRsZSI6IlN1cHBsZW1lbnRfRXZlbnRfUGFyc2VkOiIsImxvZ05hbWUiOiJjb20uYXR0LmdmcC5kY2FlLmV2ZW50UHJvY2Vzc29yLm91dHB1dCJ9LHsiY2xhc3MiOiJSdW5QaGFzZSIsInBoYXNlIjoic3VwcGxlbWVudF9wdWJsaXNoIn1dfSx7InBoYXNlIjoidm"
			+ "VzX3N1cHBsZW1lbnQiLCJmaWx0ZXIiOnsiY2xhc3MiOiJPbmVPZiIsImZpZWxkIjoiZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuZXZlbnRUeXBlIiwidmFsdWVzIjpbInZJUkNfQWxhcm1zIl19LCJwcm9jZXNzb3JzIjpbeyJjbGFzcyI6IlJ1blBoYXNlIiwicGhhc2UiOiJzdXBwbGVtZW50X3B1Ymxpc2gifV1"
			+ "9XX0nCiAgICAgICAgcGhhc2VzLnZlc19zdXBwbGVtZW50LnN0cmVhbVBhdHRlcm46IC4qc2VjLWZhdWx0LioKICAgICAgICBkZWZhdWx0Q2F0YWxvZ3M6IGNvbS5hdHQuZ2ZwLmRjYWUuZXZlbnRQcm9jZXNzb3IuQ2F0YWxvZyxjb20uYXR0LmVjb21wLmRjYWUuZXZlbnRwcm9jLmNkYXAuY29tbW9uLnByb2Nl"
			+ "c3NvcnMuQ2F0YWxvZwogICAgICAgIHBvc3RDb25maWc6ICd7InBoYXNlIjoic3VwcGxlbWVudF9wdWJsaXNoIiwicHJvY2Vzc29ycyI6W3siY2xhc3MiOiJFdmVudFByb2Nlc3Nvck1ldHJpYyIsIm1ldHJpYyI6Im91dC5ldmVudHMifSx7ImNsYXNzIjoiU2VuZEV2ZW50IiwiY2hhbm5lbCI6IjI0MjU2LURDQ"
			+ "UUtU1VQUExFTUVOVC1FVkVOVC1PVVQtdjEifV19JwogICAgICAgIHBoYXNlcy5zdXBwbGVtZW50LnN0cmVhbVBhdHRlcm46IC4qc3VwcGxlbWVudC1pbi4qCmltcG9ydHM6IFtdCnRvc2NhX2RlZmluaXRpb25zX3ZlcnNpb246IHRvc2NhX3NpbXBsZV95YW1sXzFfMF8wCg==\","
			+"\"models\":[{\"template\": \"dG9zY2FfZGVmaW5pdGlvbnNfdmVyc2lvbjogdG9zY2Ffc2ltcGxlX3lhbWxfMV8wXzANCm1ldGFkYXRhOg0KICB0ZW1wbGF0ZV9uYW1lOiBzdXBwbGVtZW50DQppbXBvcnRzOg0KLSBzY2hlbWE6IHNjaGVtYS55YW1sDQp0b3BvbG9neV90ZW1wbGF0ZToNCiAgaW5wdXRzO"
			+ "g0KICAgIGNvbm5lY3RlZF9icm9rZXJfZG5zX25hbWU6DQogICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIGRlZmF1bHQ6IGNkYXBfYnJva2VyDQogIG5vZGVfdGVtcGxhdGVzOg0KICAgIHN1cHBsZW1lbnQ6DQogICAgICB0eXBlOiB0b3NjYS5kY2FlLm5vZGVzLmNkYXBBcHAuc3VwcGxlbWVudA0KICAgICAgc"
			+ "HJvcGVydGllczoNCiAgICAgICAgY29ubmVjdGVkX2Jyb2tlcl9kbnNfbmFtZToNCiAgICAgICAgICBnZXRfaW5wdXQ6IGNvbm5lY3RlZF9icm9rZXJfZG5zX25hbWUNCiAgICAgICAgZGVmYXVsdENhdGFsb2dzOiBjb20uYXR0LmdmcC5kY2FlLmV2ZW50UHJvY2Vzc29yLkNhdGFsb2csY29tLmF0dC5lY29tc"
			+ "C5kY2FlLmV2ZW50cHJvYy5jZGFwLmNvbW1vbi5wcm9jZXNzb3JzLkNhdGFsb2cNCiAgICAgICAganNvbjogJ3sicHJvY2Vzc2luZyI6W3sicGhhc2UiOiJzdXBwbGVtZW50IiwiZmlsdGVyIjp7ImNsYXNzIjoiT25lT2YiLCJmaWVsZCI6ImV2ZW50LmNvbW1vbkV2ZW50SGVhZGVyLmV2ZW50VHlwZSIsInZhb"
			+ "HVlcyI6WyJ2UENSRl9BbGFybXMiLCJ2TW9HX0FsYXJtcyIsImFwcGxpY2F0aW9uVm5mIiwiR3Vlc3RPU19BbGFybXMiLCJDb250cm9sIl19LCJwcm9jZXNzb3JzIjpbeyJjbGFzcyI6IkxvZ1RleHQiLCJsb2dMZXZlbCI6IklORk8iLCJsb2dUZXh0IjoiRW50ZXJpbmcgc3VwcGxlbWVudCBQaGFzZSAtIEZJT"
			+ "FRFUiBwYXJhbWV0ZXIgIC0gJHtldmVudC5jb21tb25FdmVudEhlYWRlci5ldmVudFR5cGV9In0seyJjbGFzcyI6IkRhdGVGb3JtYXR0ZXIiLCJ2YWx1ZSI6IiR7ZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuc3RhcnRFcG9jaE1pY3Jvc2VjfSIsImZyb21Gb3JtYXQiOiIjbXMiLCJmcm9tVHoiOiJHTVQiLCJ0b"
			+ "0ZpZWxkIjoiZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuaW50ZXJuYWxIZWFkZXJGaWVsZHMuZmlyc3REYXRldGltZSIsInRvRm9ybWF0IjoiRUVFLCBkZCBNTSB5eXl5IEhIOm1tOnNzIHp6eiIsInRvVHoiOiJHTVQifSx7ImNsYXNzIjoiRGF0ZUZvcm1hdHRlciIsInZhbHVlIjoiJHtldmVudC5jb21tb25Fd"
			+ "mVudEhlYWRlci5sYXN0RXBvY2hNaWNyb3NlY30iLCJmcm9tRm9ybWF0IjoiI21zIiwiZnJvbVR6IjoiR01UIiwidG9GaWVsZCI6ImV2ZW50LmNvbW1vbkV2ZW50SGVhZGVyLmludGVybmFsSGVhZGVyRmllbGRzLmxhc3REYXRldGltZSIsInRvRm9ybWF0IjoiRUVFLCBkZCBNTSB5eXl5IEhIOm1tOnNzIHp6"
			+ "eiIsInRvVHoiOiJHTVQifSx7ImNsYXNzIjoiRGF0ZUZvcm1hdHRlciIsInZhbHVlIjoiJXtub3cubXN9IiwiZnJvbUZvcm1hdCI6IiNtcyIsImZyb21UeiI6IkdNVCIsInRvRmllbGQiOiJldmVudC5jb21tb25FdmVudEhlYWRlci5pbnRlcm5hbEhlYWRlckZpZWxkcy5jb2xsZWN0b3JUaW1lU3RhbXAiLCJ"
			+ "0b0Zvcm1hdCI6IkVFRSwgZGQgTU0geXl5eSBISDptbTpzcyB6enoiLCJ0b1R6IjoiR01UIn0seyJjbGFzcyI6IlNldCIsInVwZGF0ZXMiOnsiZXZlbnQuY29tbW9uRXZlbnRIZWFkZXIuaW50ZXJuYWxIZWFkZXJGaWVsZHMuaW50ZXJuYWxIZWFkZXJGaWVsZHNWZXJzaW9uIjoiOS45IiwiZXZlbnQuY29tbW"
			+ "9uRXZlbnRIZWFkZXIuaW50ZXJuYWxIZWFkZXJGaWVsZHMuZXZlbnRUYWciOiIke2hwLnRhZ30ifX1dfSx7InBoYXNlIjoic3VwcGxlbWVudCIsInByb2Nlc3NvcnMiOlt7ImNsYXNzIjoiTG9nRXZlbnRQcmV0dHkiLCJ0aXRsZSI6IlN1cHBsZW1lbnRfRXZlbnRfUGFyc2VkOiIsImxvZ05hbWUiOiJjb20u"
			+ "YXR0LmdmcC5kY2FlLmV2ZW50UHJvY2Vzc29yLm91dHB1dCJ9LHsiY2xhc3MiOiJSdW5QaGFzZSIsInBoYXNlIjoic3VwcGxlbWVudF9wdWJsaXNoIn1dfSx7InBoYXNlIjoidmVzX3N1cHBsZW1lbnQiLCJmaWx0ZXIiOnsiY2xhc3MiOiJPbmVPZiIsImZpZWxkIjoiZXZlbnQuY29tbW9uRXZlbnRIZWFkZXI"
			+ "uZXZlbnRUeXBlIiwidmFsdWVzIjpbInZJUkNfQWxhcm1zIl19LCJwcm9jZXNzb3JzIjpbeyJjbGFzcyI6IlJ1blBoYXNlIiwicGhhc2UiOiJzdXBwbGVtZW50X3B1Ymxpc2gifV19XX0nDQogICAgICAgIHBoYXNlcy5zdXBwbGVtZW50LnBoYXNlTmFtZTogc3VwcGxlbWVudA0KICAgICAgICBwaGFzZXMuc"
			+ "3VwcGxlbWVudC5zdHJlYW1QYXR0ZXJuOiAuKnN1cHBsZW1lbnQtaW4uKg0KICAgICAgICBwaGFzZXMudmVzX3N1cHBsZW1lbnQucGhhc2VOYW1lOiB2ZXNfc3VwcGxlbWVudA0KICAgICAgICBwaGFzZXMudmVzX3N1cHBsZW1lbnQuc3RyZWFtUGF0dGVybjogLipzZWMtZmF1bHQuKg0KICAgICAgICBwb3N"
			+ "0Q29uZmlnOiAneyJwaGFzZSI6InN1cHBsZW1lbnRfcHVibGlzaCIsInByb2Nlc3NvcnMiOlt7ImNsYXNzIjoiRXZlbnRQcm9jZXNzb3JNZXRyaWMiLCJtZXRyaWMiOiJvdXQuZXZlbnRzIn0seyJjbGFzcyI6IlNlbmRFdmVudCIsImNoYW5uZWwiOiIyNDI1Ni1EQ0FFLVNVUFBMRU1FTlQtRVZFTlQtT1VUL"
			+ "XYxIn1dfScNCiAgICAgIGNhcGFiaWxpdGllczoNCiAgICAgICAgc3RyZWFtX3N1YnNjcmliZV8wOg0KICAgICAgICAgIHByb3BlcnRpZXM6DQogICAgICAgICAgICBmb3JtYXQ6IFZFU19zcGVjaWZpY2F0aW9uDQogICAgICAgICAgICByb3V0ZTogSUdOT1JFDQogICAgICAgICAgICB2ZXJzaW9uOiA1Lj"
			+ "I4LjQNCiAgICAgIHJlcXVpcmVtZW50czoNCiAgICAgIC0gc3RyZWFtX3B1Ymxpc2hfMDoNCiAgICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5zdHJlYW0uc3Vic2NyaWJlDQogICAgICAgICAgcmVsYXRpb25zaGlwOiBkY2FlLnJlbGF0aW9uc2hpcHMucmV3b3JrX2Nvbm5lY3RlZF9"
			+ "0bw0KICAgICAgICAgIG5vZGVfZmlsdGVyOg0KICAgICAgICAgICAgY2FwYWJpbGl0aWVzOg0KICAgICAgICAgICAgLSBkY2FlLmNhcGFiaWxpdGllcy5zdHJlYW0uc3Vic2NyaWJlOg0KICAgICAgICAgICAgICAgIHByb3BlcnRpZXM6DQogICAgICAgICAgICAgICAgLSBmb3JtYXQ6DQogICAgICAgICAgICAg"
			+ "ICAgICAtIGVxdWFsOiBWRVNfc3BlY2lmaWNhdGlvbg0KICAgICAgICAgICAgICAgIC0gdmVyc2lvbjoNCiAgICAgICAgICAgICAgICAgIC0gZXF1YWw6IDUuMjguNA0K\","
			+"\"schema\":\"dG9zY2FfZGVmaW5pdGlvbnNfdmVyc2lvbjogdG9zY2Ffc2ltcGxlX3lhbWxfMV8wXzANCmNhcGFiaWxpdHlfdHlwZXM6DQogIGRjYWUuY2FwYWJpbGl0aWVzLmNkYXBIb3N0Og0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2EuY2FwYWJpbGl0aWVzLlJvb3QNCiAgZGNhZS5jYXBhYmlsaXRpZXMuY2"
			+ "9tcG9zaXRpb24uaG9zdDoNCiAgICBkZXJpdmVkX2Zyb206IHRvc2NhLmNhcGFiaWxpdGllcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgIGxvY2F0aW9uX2lkOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHNlcnZpY2VfaWQ6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICBkY2FlLmNhcGFiaWx"
			+ "pdGllcy5kbW1hcC5mZWVkOg0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2EuY2FwYWJpbGl0aWVzLlJvb3QNCiAgICBwcm9wZXJ0aWVzOg0KICAgICAgZmVlZF9uYW1lOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIGxvY2F0aW9uOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIG5vZGVfbmFtZToNC"
			+ "iAgICAgICAgdHlwZTogc3RyaW5nDQogIGRjYWUuY2FwYWJpbGl0aWVzLmRtbWFwLnRvcGljOg0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2EuY2FwYWJpbGl0aWVzLlJvb3QNCiAgICBwcm9wZXJ0aWVzOg0KICAgICAgYWFmX3Bhc3N3b3JkOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIGFhZl91c2Vyb"
			+ "mFtZToNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBjbGllbnRfcm9sZToNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBsb2NhdGlvbjoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBub2RlX25hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgdG9waWNfbmFtZToNCiAgICAgI"
			+ "CAgdHlwZTogc3RyaW5nDQogIGRjYWUuY2FwYWJpbGl0aWVzLmRvY2tlckhvc3Q6DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5jYXBhYmlsaXRpZXMuUm9vdA0KICBkY2FlLmNhcGFiaWxpdGllcy5wb2xpY3k6DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5jYXBhYmlsaXRpZXMuUm9vdA0KICBkY2FlLmNhc"
			+ "GFiaWxpdGllcy5zZXJ2aWNlLnByb3ZpZGU6DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5jYXBhYmlsaXRpZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICByZXF1ZXN0X2Zvcm1hdDoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICByZXF1ZXN0X3ZlcnNpb246DQogICAgICAgIHR5cGU6IHN0c"
			+ "mluZw0KICAgICAgcmVzcG9uc2VfZm9ybWF0Og0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHJlc3BvbnNlX3ZlcnNpb246DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgc2VydmljZV9lbmRwb2ludDoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBzZXJ2aWNlX25hbWU6DQogICAgICAgIH"
			+ "R5cGU6IHN0cmluZw0KICAgICAgdmVyYjoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogIGRjYWUuY2FwYWJpbGl0aWVzLnN0cmVhbS5zdWJzY3JpYmU6DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5jYXBhYmlsaXRpZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICBmb3JtYXQ6DQogICAgICAgIHR5cG"
			+ "U6IHN0cmluZw0KICAgICAgcm91dGU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgdmVyc2lvbjoNCiAgICAgICAgdHlwZTogc3RyaW5nDQpyZWxhdGlvbnNoaXBfdHlwZXM6DQogIGNsb3VkaWZ5LnJlbGF0aW9uc2hpcHMuZGVwZW5kc19vbjoNCiAgICBkZXJpdmVkX2Zyb206IHRvc2NhLnJlbGF0aW9"
			+ "uc2hpcHMuUm9vdA0KICBkY2FlLnJlbGF0aW9uc2hpcHMuY29tcG9uZW50X2NvbnRhaW5lZF9pbjoNCiAgICBkZXJpdmVkX2Zyb206IHRvc2NhLnJlbGF0aW9uc2hpcHMuUm9vdA0KICBkY2FlLnJlbGF0aW9uc2hpcHMucHVibGlzaF9ldmVudHM6DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5yZWxhdGlvbnNo"
			+ "aXBzLlJvb3QNCiAgZGNhZS5yZWxhdGlvbnNoaXBzLnB1Ymxpc2hfZmlsZXM6DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5yZWxhdGlvbnNoaXBzLlJvb3QNCiAgZGNhZS5yZWxhdGlvbnNoaXBzLnJld29ya19jb25uZWN0ZWRfdG86DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5yZWxhdGlvbnNoaXBzLlJvb"
			+ "3QNCiAgZGNhZS5yZWxhdGlvbnNoaXBzLnN1YnNjcmliZV90b19ldmVudHM6DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5yZWxhdGlvbnNoaXBzLlJvb3QNCiAgZGNhZS5yZWxhdGlvbnNoaXBzLnN1YnNjcmliZV90b19maWxlczoNCiAgICBkZXJpdmVkX2Zyb206IHRvc2NhLnJlbGF0aW9uc2hpcHMuUm9vdA"
			+ "0Kbm9kZV90eXBlczoNCiAgY2xvdWRpZnkuZGNhZS5ub2Rlcy5Sb290Og0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2Eubm9kZXMuUm9vdA0KICBkY2FlLm5vZGVzLkRvY2tlckNvbnRhaW5lckZvckNvbXBvbmVudHM6DQogICAgYXR0cmlidXRlczoNCiAgICAgIHNlcnZpY2VfY29tcG9uZW50X25hbWU6DQogICA"
			+ "gICAgIHR5cGU6IHN0cmluZw0KICAgIGRlcml2ZWRfZnJvbTogY2xvdWRpZnkuZGNhZS5ub2Rlcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgIGFwcGxpY2F0aW9uX2NvbmZpZzoNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgICAgdHlwZTogbWFwDQogICAgICBkb2NrZXJfY29uZmlnOg0KICAg"
			+ "ICAgICB0eXBlOiBtYXANCiAgICAgIGltYWdlOg0KICAgICAgICByZXF1aXJlZDogdHJ1ZQ0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIGxvY2F0aW9uX2lkOg0KICAgICAgICByZXF1aXJlZDogdHJ1ZQ0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHNlcnZpY2VfY29tcG9uZW50X3R5cGU6DQogI"
			+ "CAgICAgIHJlcXVpcmVkOiB0cnVlDQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgIHJlcXVpcmVtZW50czoNCiAgICAtIGhvc3Q6DQogICAgICAgIGNhcGFiaWxpdHk6IGRjYWUuY2FwYWJpbGl0aWVzLmRvY2tlckhvc3QNCiAgICAgICAgcmVsYXRpb25zaGlwOiBkY2FlLnJlbGF0aW9uc2hpcHMuY29tcG9uZW"
			+ "50X2NvbnRhaW5lZF9pbg0KICBkY2FlLm5vZGVzLkRvY2tlckNvbnRhaW5lckZvckNvbXBvbmVudHNVc2luZ0RtYWFwOg0KICAgIGRlcml2ZWRfZnJvbTogZGNhZS5ub2Rlcy5Eb2NrZXJDb250YWluZXJGb3JDb21wb25lbnRzDQogICAgcHJvcGVydGllczoNCiAgICAgIHN0cmVhbXNfcHVibGlzaGVzOg0KICA"
			+ "gICAgICB0eXBlOiBsaXN0DQogICAgICBzdHJlYW1zX3N1YnNjcmliZXM6DQogICAgICAgIHR5cGU6IGxpc3QNCiAgZGNhZS5ub2Rlcy5FeGlzdGluZ0ZlZWQ6DQogICAgY2FwYWJpbGl0aWVzOg0KICAgICAgZmVlZDoNCiAgICAgICAgdHlwZTogZGNhZS5jYXBhYmlsaXRpZXMuZG1tYXAuZmVlZA0KICAgIGRl"
			+ "cml2ZWRfZnJvbTogY2xvdWRpZnkuZGNhZS5ub2Rlcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgIGZlZWRfaWQ6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICBkY2FlLm5vZGVzLkV4aXN0aW5nVG9waWM6DQogICAgY2FwYWJpbGl0aWVzOg0KICAgICAgdG9waWM6DQogICAgICAgIHR5cGU6IGRjYWUuY"
			+ "2FwYWJpbGl0aWVzLmRtbWFwLnRvcGljDQogICAgZGVyaXZlZF9mcm9tOiBjbG91ZGlmeS5kY2FlLm5vZGVzLlJvb3QNCiAgICBwcm9wZXJ0aWVzOg0KICAgICAgZnF0bjoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogIGRjYWUubm9kZXMuRXh0ZXJuYWxUYXJnZXRGZWVkOg0KICAgIGNhcGFiaWxpdGllczoNCi"
			+ "AgICAgIGZlZWQ6DQogICAgICAgIHR5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLmRtbWFwLmZlZWQNCiAgICBkZXJpdmVkX2Zyb206IGNsb3VkaWZ5LmRjYWUubm9kZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICB1cmw6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgdXNlcm5hbWU6DQogICAgICA"
			+ "gIHR5cGU6IHN0cmluZw0KICAgICAgdXNlcnB3Og0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgZGNhZS5ub2Rlcy5GZWVkOg0KICAgIGNhcGFiaWxpdGllczoNCiAgICAgIGZlZWQ6DQogICAgICAgIHR5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLmRtbWFwLmZlZWQNCiAgICBkZXJpdmVkX2Zyb206IGNsb3VkaWZ5"
			+ "LmRjYWUubm9kZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICBmZWVkX25hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICBkY2FlLm5vZGVzLk1pY3JvU2VydmljZS5jZGFwOg0KICAgIGRlcml2ZWRfZnJvbTogY2xvdWRpZnkuZGNhZS5ub2Rlcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgI"
			+ "GFwcF9jb25maWc6DQogICAgICAgIHJlcXVpcmVkOiBmYWxzZQ0KICAgICAgICB0eXBlOiBtYXANCiAgICAgIGFwcF9wcmVmZXJlbmNlczoNCiAgICAgICAgcmVxdWlyZWQ6IGZhbHNlDQogICAgICAgIHR5cGU6IG1hcA0KICAgICAgYXJ0aWZhY3RfbmFtZToNCiAgICAgICAgcmVxdWlyZWQ6IGZhbHNlDQogIC"
			+ "AgICAgIHR5cGU6IHN0cmluZw0KICAgICAgYXJ0aWZhY3RfdmVyc2lvbjoNCiAgICAgICAgcmVxdWlyZWQ6IGZhbHNlDQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgY29ubmVjdGlvbnM6DQogICAgICAgIHJlcXVpcmVkOiBmYWxzZQ0KICAgICAgICB0eXBlOiBtYXANCiAgICAgIGphcl91cmw6DQogICA"
			+ "gICAgIHR5cGU6IHN0cmluZw0KICAgICAgbmFtZXNwYWNlOg0KICAgICAgICByZXF1aXJlZDogZmFsc2UNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBwcm9ncmFtX3ByZWZlcmVuY2VzOg0KICAgICAgICByZXF1aXJlZDogZmFsc2UNCiAgICAgICAgdHlwZTogbGlzdA0KICAgICAgcHJvZ3JhbXM6DQog"
			+ "ICAgICAgIHJlcXVpcmVkOiBmYWxzZQ0KICAgICAgICB0eXBlOiBsaXN0DQogICAgICBzZXJ2aWNlX2NvbXBvbmVudF90eXBlOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHNlcnZpY2VfZW5kcG9pbnRzOg0KICAgICAgICByZXF1aXJlZDogZmFsc2UNCiAgICAgICAgdHlwZTogbGlzdA0KICAgICAgc"
			+ "3RyZWFtbmFtZToNCiAgICAgICAgcmVxdWlyZWQ6IGZhbHNlDQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgIGF0dHJpYnV0ZXM6DQogICAgICBzZXJ2aWNlX2NvbXBvbmVudF9uYW1lOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICBjYXBhYmlsaXRpZXM6DQogICAgICBzdHJlYW1fc3Vic2NyaWJlXzA6DQ"
			+ "ogICAgICAgIHR5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLnN0cmVhbS5zdWJzY3JpYmUNCiAgICByZXF1aXJlbWVudHM6DQogICAgLSBob3N0Og0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5jZGFwSG9zdA0KICAgICAgICByZWxhdGlvbnNoaXA6IGRjYWUucmVsYXRpb25zaGlwcy5jb2"
			+ "1wb25lbnRfY29udGFpbmVkX2luDQogICAgLSBzdHJlYW1fcHVibGlzaF8wOg0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5zdHJlYW0uc3Vic2NyaWJlDQogICAgICAgIHJlbGF0aW9uc2hpcDogZGNhZS5yZWxhdGlvbnNoaXBzLnJld29ya19jb25uZWN0ZWRfdG8NCiAgICBpbnRlcmZ"
			+ "hY2VzOg0KICAgICAgY2xvdWRpZnkuaW50ZXJmYWNlcy5saWZlY3ljbGU6DQogICAgICAgIGNyZWF0ZToNCiAgICAgICAgICBpbnB1dHM6DQogICAgICAgICAgICBjb25uZWN0ZWRfYnJva2VyX2Ruc19uYW1lOg0KICAgICAgICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgICAgdHlwZTogdG9zY2EuaW50ZXJ"
			+ "mYWNlcy5Sb290DQogIGRjYWUubm9kZXMuU2VsZWN0ZWREb2NrZXJIb3N0Og0KICAgIGNhcGFiaWxpdGllczoNCiAgICAgIGhvc3Q6DQogICAgICAgIHR5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLmRvY2tlckhvc3QNCiAgICBkZXJpdmVkX2Zyb206IGNsb3VkaWZ5LmRjYWUubm9kZXMuUm9vdA0KICAgIHByb3B"
			+ "lcnRpZXM6DQogICAgICBkb2NrZXJfaG9zdF9vdmVycmlkZToNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBsb2NhdGlvbl9pZDoNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgICAgdHlwZTogc3RyaW5nDQogIGRjYWUubm9kZXMuVG9waWM6DQogICAgY2FwYWJpbGl0aWVzOg0KICAgICAgdG9w"
			+ "aWM6DQogICAgICAgIHR5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLmRtbWFwLnRvcGljDQogICAgZGVyaXZlZF9mcm9tOiBjbG91ZGlmeS5kY2FlLm5vZGVzLlJvb3QNCiAgICBwcm9wZXJ0aWVzOg0KICAgICAgdG9waWNfbmFtZToNCiAgICAgICAgdHlwZTogc3RyaW5nDQogIGRjYWUubm9kZXMuY29tcG9zaXRpb"
			+ "24udmlydHVhbDoNCiAgICBjYXBhYmlsaXRpZXM6DQogICAgICBob3N0Og0KICAgICAgICB0eXBlOiBkY2FlLmNhcGFiaWxpdGllcy5jb21wb3NpdGlvbi5ob3N0DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5ub2Rlcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgIGxvY2F0aW9uX2lkOg0KICAgICAgIC"
			+ "ByZXF1aXJlZDogdHJ1ZQ0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHNlcnZpY2VfaWQ6DQogICAgICAgIHJlcXVpcmVkOiB0cnVlDQogICAgICAgIHR5cGU6IHN0cmluZw0KICBkY2FlLm5vZGVzLnBvbGljeToNCiAgICBjYXBhYmlsaXRpZXM6DQogICAgICBwb2xpY3k6DQogICAgICAgIHR5cGU6IGR"
			+ "jYWUuY2FwYWJpbGl0aWVzLnBvbGljeQ0KICAgIGRlcml2ZWRfZnJvbTogY2xvdWRpZnkuZGNhZS5ub2Rlcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgIHBvbGljeV9pZDoNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgICAgdHlwZTogc3RyaW5nDQogIHBvbGljeS5ub2Rlcy5Sb290Og0KICAg"
			+ "IGRlcml2ZWRfZnJvbTogdG9zY2Eubm9kZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICBwb2xpY3lEZXNjcmlwdGlvbjoNCiAgICAgICAgcmVxdWlyZWQ6IGZhbHNlDQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgcG9saWN5TmFtZToNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgICAgd"
			+ "HlwZTogc3RyaW5nDQogICAgICBwb2xpY3lTY29wZToNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBwb2xpY3lWZXJzaW9uOg0KICAgICAgICByZXF1aXJlZDogdHJ1ZQ0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgdG9zY2EuZGNhZS5ub2Rlcy5Sb290Og0KIC"
			+ "AgIGRlcml2ZWRfZnJvbTogdG9zY2Eubm9kZXMuUm9vdA0KICB0b3NjYS5kY2FlLm5vZGVzLmNkYXBBcHA6DQogICAgYXR0cmlidXRlczoNCiAgICAgIHNlcnZpY2VfY29tcG9uZW50X25hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2EuZGNhZS5ub2Rlcy5Sb290DQ"
			+ "ogICAgcHJvcGVydGllczoNCiAgICAgIGNvbm5lY3RlZF9icm9rZXJfZG5zX25hbWU6DQogICAgICAgIGRlZmF1bHQ6IGNkYXBfYnJva2VyDQogICAgICAgIHJlcXVpcmVkOiB0cnVlDQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgamFyX3VybDoNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgIC"
			+ "AgdHlwZTogc3RyaW5nDQogICAgICBzZXJ2aWNlX2NvbXBvbmVudF90eXBlOg0KICAgICAgICByZXF1aXJlZDogdHJ1ZQ0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICByZXF1aXJlbWVudHM6DQogICAgLSBob3N0Og0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5jZGFwSG9zdA0KICA"
			+ "gICAgICByZWxhdGlvbnNoaXA6IGRjYWUucmVsYXRpb25zaGlwcy5jb21wb25lbnRfY29udGFpbmVkX2luDQogIHRvc2NhLmRjYWUubm9kZXMuY2RhcEFwcC5zdXBwbGVtZW50Og0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2EuZGNhZS5ub2Rlcy5jZGFwQXBwDQogICAgcHJvcGVydGllczoNCiAgICAgIGRlZmF"
			+ "1bHRDYXRhbG9nczoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBqc29uOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHBoYXNlcy5zdXBwbGVtZW50LnBoYXNlTmFtZToNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBwaGFzZXMuc3VwcGxlbWVudC5zdHJlYW1QYXR0ZXJuOg0KICAgICAg"
			+ "ICB0eXBlOiBzdHJpbmcNCiAgICAgIHBoYXNlcy52ZXNfc3VwcGxlbWVudC5waGFzZU5hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgcGhhc2VzLnZlc19zdXBwbGVtZW50LnN0cmVhbVBhdHRlcm46DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgcG9zdENvbmZpZzoNCiAgICAgICAgdHlwZ"
			+ "Togc3RyaW5nDQogICAgY2FwYWJpbGl0aWVzOg0KICAgICAgc3RyZWFtX3N1YnNjcmliZV8wOg0KICAgICAgICB0eXBlOiBkY2FlLmNhcGFiaWxpdGllcy5zdHJlYW0uc3Vic2NyaWJlDQogICAgcmVxdWlyZW1lbnRzOg0KICAgIC0gc3RyZWFtX3B1Ymxpc2hfMDoNCiAgICAgICAgY2FwYWJpbGl0eTogZGNhZS"
			+ "5jYXBhYmlsaXRpZXMuc3RyZWFtLnN1YnNjcmliZQ0KICAgICAgICByZWxhdGlvbnNoaXA6IGRjYWUucmVsYXRpb25zaGlwcy5yZXdvcmtfY29ubmVjdGVkX3RvDQogIHRvc2NhLmRjYWUubm9kZXMuZG1hYXAuZXhpc3RpbmdGZWVkOg0KICAgIGNhcGFiaWxpdGllczoNCiAgICAgIGZlZWQ6DQogICAgICAgIHR"
			+ "5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLmRtbWFwLmZlZWQNCiAgICBkZXJpdmVkX2Zyb206IHRvc2NhLmRjYWUubm9kZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICBmZWVkX2lkOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIGxvY2F0aW9uOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAg"
			+ "IG5vZGVfbmFtZToNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgcmVxdWlyZW1lbnRzOg0KICAgIC0gY29tcG9zaXRpb246DQogICAgICAgIGNhcGFiaWxpdHk6IGRjYWUuY2FwYWJpbGl0aWVzLmNvbXBvc2l0aW9uLmhvc3QNCiAgdG9zY2EuZGNhZS5ub2Rlcy5kbWFhcC5leGlzdGluZ1RvcGljOg0KICAg"
			+ "IGNhcGFiaWxpdGllczoNCiAgICAgIHRvcGljOg0KICAgICAgICB0eXBlOiBkY2FlLmNhcGFiaWxpdGllcy5kbW1hcC50b3BpYw0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2EuZGNhZS5ub2Rlcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgIGFhZl9wYXNzd29yZDoNCiAgICAgICAgdHlwZTogc3RyaW5nDQ"
			+ "ogICAgICBhYWZfdXNlcm5hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgY2xpZW50X3JvbGU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgZnF0bjoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBsb2NhdGlvbjoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBub2RlX25hbWU6"
			+ "DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgIHJlcXVpcmVtZW50czoNCiAgICAtIGNvbXBvc2l0aW9uOg0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5jb21wb3NpdGlvbi5ob3N0DQogIHRvc2NhLmRjYWUubm9kZXMuZG1hYXAuZXh0ZXJuYWxUYXJnZXRGZWVkOg0KICAgIGNhcGFiaW"
			+ "xpdGllczoNCiAgICAgIGZlZWQ6DQogICAgICAgIHR5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLmRtbWFwLmZlZWQNCiAgICBkZXJpdmVkX2Zyb206IHRvc2NhLmRjYWUubm9kZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICBsb2NhdGlvbjoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBub2RlX25"
			+ "hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgdXJsOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHVzZXJuYW1lOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHVzZXJwdzoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgcmVxdWlyZW1lbnRzOg0KICAgIC0gY29tcG9zaXRpb246"
			+ "DQogICAgICAgIGNhcGFiaWxpdHk6IGRjYWUuY2FwYWJpbGl0aWVzLmNvbXBvc2l0aW9uLmhvc3QNCiAgdG9zY2EuZGNhZS5ub2Rlcy5kbWFhcC5mZWVkOg0KICAgIGNhcGFiaWxpdGllczoNCiAgICAgIGZlZWQ6DQogICAgICAgIHR5cGU6IGRjYWUuY2FwYWJpbGl0aWVzLmRtbWFwLmZlZWQNCiAgICBkZXJpd"
			+ "mVkX2Zyb206IHRvc2NhLmRjYWUubm9kZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICBmZWVkX25hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgbG9jYXRpb246DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgbm9kZV9uYW1lOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICByZX"
			+ "F1aXJlbWVudHM6DQogICAgLSBjb21wb3NpdGlvbjoNCiAgICAgICAgY2FwYWJpbGl0eTogZGNhZS5jYXBhYmlsaXRpZXMuY29tcG9zaXRpb24uaG9zdA0KICB0b3NjYS5kY2FlLm5vZGVzLmRtYWFwLnRvcGljOg0KICAgIGNhcGFiaWxpdGllczoNCiAgICAgIHRvcGljOg0KICAgICAgICB0eXBlOiBkY2FlLmN"
			+ "hcGFiaWxpdGllcy5kbW1hcC50b3BpYw0KICAgIGRlcml2ZWRfZnJvbTogdG9zY2EuZGNhZS5ub2Rlcy5Sb290DQogICAgcHJvcGVydGllczoNCiAgICAgIGFhZl9wYXNzd29yZDoNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBhYWZfdXNlcm5hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAg"
			+ "Y2xpZW50X3JvbGU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgbG9jYXRpb246DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgICAgbm9kZV9uYW1lOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHRvcGljX25hbWU6DQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgIHJlcXVpcmVtZW50czoNC"
			+ "iAgICAtIGNvbXBvc2l0aW9uOg0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5jb21wb3NpdGlvbi5ob3N0DQogIHRvc2NhLmRjYWUubm9kZXMuZG9ja2VyQXBwOg0KICAgIGF0dHJpYnV0ZXM6DQogICAgICBzZXJ2aWNlX2NvbXBvbmVudF9uYW1lOg0KICAgICAgICB0eXBlOiBzdHJpb"
			+ "mcNCiAgICBkZXJpdmVkX2Zyb206IHRvc2NhLmRjYWUubm9kZXMuUm9vdA0KICAgIHByb3BlcnRpZXM6DQogICAgICBpbWFnZToNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgICAgdHlwZTogc3RyaW5nDQogICAgICBsb2NhdGlvbl9pZDoNCiAgICAgICAgcmVxdWlyZWQ6IHRydWUNCiAgICAgICAgd"
			+ "HlwZTogc3RyaW5nDQogICAgICBzZXJ2aWNlX2NvbXBvbmVudF90eXBlOg0KICAgICAgICByZXF1aXJlZDogdHJ1ZQ0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICByZXF1aXJlbWVudHM6DQogICAgLSBob3N0Og0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5kb2NrZXJIb3N0DQogI"
			+ "CAgICAgIHJlbGF0aW9uc2hpcDogZGNhZS5yZWxhdGlvbnNoaXBzLmNvbXBvbmVudF9jb250YWluZWRfaW4NCiAgICAtIGNvbXBvc2l0aW9uOg0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5jb21wb3NpdGlvbi5ob3N0DQogIHRvc2NhLmRjYWUubm9kZXMuZG9ja2VySG9zdDoNCiAgIC"
			+ "BjYXBhYmlsaXRpZXM6DQogICAgICBob3N0Og0KICAgICAgICB0eXBlOiBkY2FlLmNhcGFiaWxpdGllcy5kb2NrZXJIb3N0DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5kY2FlLm5vZGVzLlJvb3QNCiAgICBwcm9wZXJ0aWVzOg0KICAgICAgZG9ja2VyX2hvc3Rfb3ZlcnJpZGU6DQogICAgICAgIHR5cGU6IHN"
			+ "0cmluZw0KICAgICAgbG9jYXRpb25faWQ6DQogICAgICAgIHJlcXVpcmVkOiB0cnVlDQogICAgICAgIHR5cGU6IHN0cmluZw0KICAgIHJlcXVpcmVtZW50czoNCiAgICAtIGNvbXBvc2l0aW9uOg0KICAgICAgICBjYXBhYmlsaXR5OiBkY2FlLmNhcGFiaWxpdGllcy5jb21wb3NpdGlvbi5ob3N0DQogIHRvc2Nh"
			+ "LmRjYWUubm9kZXMucG9saWN5Og0KICAgIGNhcGFiaWxpdGllczoNCiAgICAgIHBvbGljeToNCiAgICAgICAgdHlwZTogZGNhZS5jYXBhYmlsaXRpZXMucG9saWN5DQogICAgZGVyaXZlZF9mcm9tOiB0b3NjYS5kY2FlLm5vZGVzLlJvb3QNCiAgICBwcm9wZXJ0aWVzOg0KICAgICAgcG9saWN5X2lkOg0KICAgI"
			+ "CAgICByZXF1aXJlZDogdHJ1ZQ0KICAgICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIHBvbGljeV9uYW1lOg0KICAgICAgICB0eXBlOiBzdHJpbmcNCg==\","
			+"\"translate\": \"dG9zY2FfZGVmaW5pdGlvbnNfdmVyc2lvbjogdG9zY2Ffc2ltcGxlX3lhbWxfMV8wXzANCm1ldGFkYXRhOg0KICB0ZW1wbGF0ZV9uYW1lOiBzdXBwbGVtZW50X3RyYW5zbGF0ZQ0KaW1wb3J0czoNCi0gJzAnOiBodHRwOi8vZG9ja2VyY2VudHJhbC5pdC5hdHQuY29tOjgwOTMvbmV4dXMvcm"
			+ "Vwb3NpdG9yeS9yYXdjZW50cmFsL2NvbS5hdHQuZGNhZS5jb250cm9sbGVyL3R5cGVfZmlsZXMvZG9ja2VycGx1Z2luLzIuNC4wK3QuMC44L25vZGUtdHlwZS55YW1sDQotICcxJzogaHR0cDovL2RvY2tlcmNlbnRyYWwuaXQuYXR0LmNvbTo4MDkzL25leHVzL3JlcG9zaXRvcnkvcmF3Y2VudHJhbC9jb20uYXR0"
			+ "LmRjYWUuY29udHJvbGxlci90eXBlX2ZpbGVzL2RtYWFwLzEuMi4wK3QuMC45L2RtYWFwLnlhbWwNCi0gJzInOiBodHRwOi8vZG9ja2VyY2VudHJhbC5pdC5hdHQuY29tOjgwOTMvbmV4dXMvcmVwb3NpdG9yeS9yYXdjZW50cmFsL2NvbS5hdHQuZGNhZS5jb250cm9sbGVyL3R5cGVfZmlsZXMvcmVsYXRpb25za"
			+ "GlwLzEuMC4wK3QuMC4xL3JlbGF0aW9uc2hpcC10eXBlcy55YW1sDQp0b3BvbG9neV90ZW1wbGF0ZToNCiAgaW5wdXRzOg0KICAgIGNvbm5lY3RlZF9icm9rZXJfZG5zX25hbWU6DQogICAgICB0eXBlOiBzdHJpbmcNCiAgICAgIGRlZmF1bHQ6IGNkYXBfYnJva2VyDQogICAgZGVmYXVsdENhdGFsb2dzOg0KIC"
			+ "AgICAgdHlwZTogc3RyaW5nDQogICAgamFyX3VybDoNCiAgICAgIHR5cGU6IHN0cmluZw0KICAgIGpzb246DQogICAgICB0eXBlOiBzdHJpbmcNCiAgICBwaGFzZXMuc3VwcGxlbWVudC5waGFzZU5hbWU6DQogICAgICB0eXBlOiBzdHJpbmcNCiAgICBwaGFzZXMuc3VwcGxlbWVudC5zdHJlYW1QYXR0ZXJuOg0"
			+ "KICAgICAgdHlwZTogc3RyaW5nDQogICAgcGhhc2VzLnZlc19zdXBwbGVtZW50LnBoYXNlTmFtZToNCiAgICAgIHR5cGU6IHN0cmluZw0KICAgIHBoYXNlcy52ZXNfc3VwcGxlbWVudC5zdHJlYW1QYXR0ZXJuOg0KICAgICAgdHlwZTogc3RyaW5nDQogICAgcG9zdENvbmZpZzoNCiAgICAgIHR5cGU6IHN0cmlu"
			+ "Zw0KICAgIHNlcnZpY2VfY29tcG9uZW50X3R5cGU6DQogICAgICB0eXBlOiBzdHJpbmcNCiAgc3Vic3RpdHV0aW9uX21hcHBpbmdzOg0KICAgIG5vZGVfdHlwZTogdG9zY2EuZGNhZS5ub2Rlcy5jZGFwQXBwLnN1cHBsZW1lbnQNCiAgICBjYXBhYmlsaXRpZXM6DQogICAgICBzdHJlYW1fc3Vic2NyaWJlXzA6D"
			+ "QogICAgICAtIHN1cHBsZW1lbnQNCiAgICAgIC0gc3RyZWFtX3N1YnNjcmliZV8wDQogICAgcmVxdWlyZW1lbnRzOg0KICAgICAgaG9zdDoNCiAgICAgIC0gc3VwcGxlbWVudA0KICAgICAgLSBob3N0DQogICAgICBzdHJlYW1fcHVibGlzaF8wOg0KICAgICAgLSBzdXBwbGVtZW50DQogICAgICAtIHN0cmVhbV"
			+ "9wdWJsaXNoXzANCiAgbm9kZV90ZW1wbGF0ZXM6DQogICAgc3VwcGxlbWVudDoNCiAgICAgIHR5cGU6IGRjYWUubm9kZXMuTWljcm9TZXJ2aWNlLmNkYXANCiAgICAgIHByb3BlcnRpZXM6DQogICAgICAgIGFwcF9jb25maWc6DQogICAgICAgICAgZGVzY3JpcHRpb246IFN1cHBsZW1lbnQgTWljcm9zZXJ2aWN"
			+ "lDQogICAgICAgICAgZXZlbnRGYWN0b3J5OiAnJw0KICAgICAgICAgIG1vbml0b3JUaHJlYWRzOiB0cnVlDQogICAgICAgICAgbmFtZTogc3VwcGxlbWVudE1TDQogICAgICAgICAgcnVsZUtleVBhdHRlcm46IHZuZlR5cGVzLioNCiAgICAgICAgICBzdGFydE5vQ2hhbm5lbHM6IGZhbHNlDQogICAgICAgIGFw"
			+ "cF9wcmVmZXJlbmNlczoNCiAgICAgICAgICBkZWZhdWx0Q2F0YWxvZ3M6DQogICAgICAgICAgICBnZXRfaW5wdXQ6IGRlZmF1bHRDYXRhbG9ncw0KICAgICAgICAgIGRlZmF1bHRPYmplY3RzOiAnJw0KICAgICAgICAgIGRtYWFwQ29uc3VtZXJHcnA6IERDQUUtQ0RBUC1TVVBQTEVNRU5ULU1TDQogICAgICAgI"
			+ "CAganNvbjoNCiAgICAgICAgICAgIGdldF9pbnB1dDoganNvbg0KICAgICAgICAgIHBoYXNlcy5zdXBwbGVtZW50LnBoYXNlTmFtZToNCiAgICAgICAgICAgIGdldF9pbnB1dDogcGhhc2VzLnN1cHBsZW1lbnQucGhhc2VOYW1lDQogICAgICAgICAgcGhhc2VzLnN1cHBsZW1lbnQuc3RyZWFtUGF0dGVybjoNCi"
			+ "AgICAgICAgICAgIGdldF9pbnB1dDogcGhhc2VzLnN1cHBsZW1lbnQuc3RyZWFtUGF0dGVybg0KICAgICAgICAgIHBoYXNlcy52ZXNfc3VwcGxlbWVudC5waGFzZU5hbWU6DQogICAgICAgICAgICBnZXRfaW5wdXQ6IHBoYXNlcy52ZXNfc3VwcGxlbWVudC5waGFzZU5hbWUNCiAgICAgICAgICBwaGFzZXMudm"
			+ "VzX3N1cHBsZW1lbnQuc3RyZWFtUGF0dGVybjoNCiAgICAgICAgICAgIGdldF9pbnB1dDogcGhhc2VzLnZlc19zdXBwbGVtZW50LnN0cmVhbVBhdHRlcm4NCiAgICAgICAgICBwb3N0Q29uZmlnOg0KICAgICAgICAgICAgZ2V0X2lucHV0OiBwb3N0Q29uZmlnDQogICAgICAgIGFydGlmYWN0X25hbWU6IGRjYWU"
			+ "tZXZlbnQtcHJvYy1jZGFwLXN1cHBsZW1lbnQNCiAgICAgICAgYXJ0aWZhY3RfdmVyc2lvbjogMS4wLjE2DQogICAgICAgIGNvbm5lY3Rpb25zOg0KICAgICAgICAgIHN0cmVhbXNfcHVibGlzaGVzOiBbXQ0KICAgICAgICAgIHN0cmVhbXNfc3Vic2NyaWJlczogW10NCiAgICAgICAgamFyX3VybDogaHR0cDo"
			+ "vL21hdmVuY2VudHJhbC5pdC5hdHQuY29tOjgwODQvbmV4dXMvY29udGVudC9yZXBvc2l0b3JpZXMvYXR0LXJlcG9zaXRvcnktcmVsZWFzZXMvY29tL2F0dC9lY29tcC9kY2FlL2V2ZW50cHJvYy9kY2FlLWV2ZW50LXByb2MtY2RhcC1zdXBwbGVtZW50LzEuMC4xNi9kY2FlLWV2ZW50LXByb2MtY2RhcC1zdXB"
			+ "wbGVtZW50LTEuMC4xNi5qYXINCiAgICAgICAgbmFtZXNwYWNlOiBldmVudF9wcm9jX3N1cHBsZW1lbnQNCiAgICAgICAgcHJvZ3JhbXM6DQogICAgICAgIC0gcHJvZ3JhbV9pZDogc3VwcGxlbWVudE1TV29ya2VyDQogICAgICAgICAgcHJvZ3JhbV90eXBlOiB3b3JrZXJzDQogICAgICAgIHNlcnZpY2VfY29"
			+ "tcG9uZW50X3R5cGU6IGNkYXBfYXBwX3N1cHBsZW1lbnQNCiAgICAgICAgc3RyZWFtbmFtZTogaW5wdXRfc3RyZWFtDQogICAgICBpbnRlcmZhY2VzOg0KICAgICAgICBjbG91ZGlmeS5pbnRlcmZhY2VzLmxpZmVjeWNsZToNCiAgICAgICAgICB0eXBlOiB0b3NjYS5pbnRlcmZhY2VzLlJvb3QNCiAgICAgICA"
			+ "gICBjcmVhdGU6DQogICAgICAgICAgICBpbnB1dHM6DQogICAgICAgICAgICAgIGNvbm5lY3RlZF9icm9rZXJfZG5zX25hbWU6DQogICAgICAgICAgICAgICAgZ2V0X2lucHV0OiBjb25uZWN0ZWRfYnJva2VyX2Ruc19uYW1lDQo=\"}]}";

	private String expectedOutput = "tosca_definitions_version: cloudify_dsl_1_3\nimports:\n- http://dockercentral.it.att.com:8093/nexus/repository/rawcentral/com.att.dcae.controller/type_files/dockerplugin/2.4.0+t.0.8/node-type.yaml\n"
			+ "- http://dockercentral.it.att.com:8093/nexus/repository/rawcentral/com.att.dcae.controller/type_files/dmaap/1.2.0+t.0.9/dmaap.yaml\n- http://dockercentral.it.att.com:8093/nexus/repository/rawcentral/com.att.dcae.controller/type_files/relationship/1.0.0+t.0.1/relationship-types.yaml\n"
			+ "inputs:\n  sup.supplement_n.1525781976500.8_connected_broker_dns_name:\n"
	        + "    type: string\n    default: cdap_broker\nnode_templates:\n  sup.supplement_n.1525781976500.8_supplement:\n    type: dcae.nodes.MicroService.cdap\n    properties:\n      app_config:\n        "
	        + "description: Supplement Microservice\n        eventFactory: ''\n        monitorThreads: true\n        name: supplementMS\n        ruleKeyPattern: vnfTypes.*\n        startNoChannels: false\n      app_preferences:\n"
	        + "        defaultCatalogs: com.att.gfp.dcae.eventProcessor.Catalog,com.att.ecomp.dcae.eventproc.cdap.common.processors.Catalog\n        defaultObjects: ''\n        dmaapConsumerGrp: DCAE-CDAP-SUPPLEMENT-MS\n        "
	        + "json: '{\"processing\":[{\"phase\":\"supplement\",\"filter\":{\"class\":\"OneOf\",\"field\":\"event.commonEventHeader.eventType\",\"values\":[\"vPCRF_Alarms\",\"vMoG_Alarms\",\"applicationVnf\",\"GuestOS_Alarms\",\"Control\"]},"
			+ "\"processors\":[{\"class\":\"LogText\",\"logLevel\":\"INFO\",\"logText\":\"Entering supplement Phase - FILTER parameter  - ${event.commonEventHeader.eventType}\"},{\"class\":\"DateFormatter\","
			+ "\"value\":\"${event.commonEventHeader.startEpochMicrosec}\",\"fromFormat\":\"#ms\",\"fromTz\":\"GMT\",\"toField\":\"event.commonEventHeader.internalHeaderFields.firstDatetime\",\"toFormat\":\"EEE, dd MM yyyy HH:mm:ss zzz\","
			+ "\"toTz\":\"GMT\"},{\"class\":\"DateFormatter\",\"value\":\"${event.commonEventHeader.lastEpochMicrosec}\",\"fromFormat\":\"#ms\",\"fromTz\":\"GMT\",\"toField\":\"event.commonEventHeader.internalHeaderFields.lastDatetime\","
			+ "\"toFormat\":\"EEE, dd MM yyyy HH:mm:ss zzz\",\"toTz\":\"GMT\"},{\"class\":\"DateFormatter\",\"value\":\"%{now.ms}\",\"fromFormat\":\"#ms\",\"fromTz\":\"GMT\","
			+ "\"toField\":\"event.commonEventHeader.internalHeaderFields.collectorTimeStamp\",\"toFormat\":\"EEE, dd MM yyyy HH:mm:ss zzz\",\"toTz\":\"GMT\"},{\"class\":\"Set\",\"updates\":"
			+ "{\"event.commonEventHeader.internalHeaderFields.internalHeaderFieldsVersion\":\"9.9\",\"event.commonEventHeader.internalHeaderFields.eventTag\":\"${hp.tag}\"}}]},{\"phase\":\"supplement\",\"processors\":[{\"class\":\"LogEventPretty\","
			+ "\"title\":\"Supplement_Event_Parsed:\",\"logName\":\"com.att.gfp.dcae.eventProcessor.output\"},{\"class\":\"RunPhase\",\"phase\":\"supplement_publish\"}]},{\"phase\":\"ves_supplement\",\"filter\":{\"class\":\"OneOf\","
			+ "\"field\":\"event.commonEventHeader.eventType\",\"values\":[\"vIRC_Alarms\"]},\"processors\":[{\"class\":\"RunPhase\",\"phase\":\"supplement_publish\"}]}]}'\n        phases.supplement.phaseName: supplement\n        "
	        + "phases.supplement.streamPattern: .*supplement-in.*\n        phases.ves_supplement.phaseName: ves_supplement\n        phases.ves_supplement.streamPattern: .*sec-fault.*\n        postConfig: '{\"phase\":\"supplement_publish\","
			+ "\"processors\":[{\"class\":\"EventProcessorMetric\",\"metric\":\"out.events\"},{\"class\":\"SendEvent\",\"channel\":\"24256-DCAE-SUPPLEMENT-EVENT-OUT-v1\"}]}'\n      artifact_name: dcae-event-proc-cdap-supplement\n      "
	        + "artifact_version: 1.0.16\n      connections:\n        streams_publishes: []\n        streams_subscribes: []\n      "
	        + "jar_url: http://mavencentral.it.att.com:8084/nexus/content/repositories/att-repository-releases/com/att/ecomp/dcae/eventproc/dcae-event-proc-cdap-supplement/1.0.16/dcae-event-proc-cdap-supplement-1.0.16.jar\n      "
	        + "namespace: event_proc_supplement\n      programs:\n      - program_id: supplementMSWorker\n        program_type: workers\n      service_component_type: cdap_app_supplement\n      streamname: input_stream\n    interfaces:\n"
	        + "      cloudify.interfaces.lifecycle:\n        create:\n          inputs:\n            connected_broker_dns_name:\n              get_input: sup.supplement_n.1525781976500.8_connected_broker_dns_name\n";

	@Test
    // already covered by HealthCheckTest since ToscaLab healthCheck is a component in the DCAE BE aggregated healthCheck
	public void healthCheckSuccessTest() throws IOException{
		RestResponse res = DcaeRestClient.getToscaLabHealthCheck();
		Report.log(Status.INFO, "HealthCheck response: " + res.getResponse());
		HealthResponse hc = gson.fromJson(res.getResponse(),HealthResponse.class);
		assertThat(res.getStatusCode()).isEqualTo(200);
		assertThat(hc.getHealthCheckComponent()).isEqualTo("TOSCA_LAB");
		assertThat(hc.getHealthCheckStatus()).isEqualTo("UP");
		assertThat(hc.getDescription()).isEqualTo("OK");
	}

	@Test
	public void translateToBlueprintSuccessTest() throws IOException {
		RestResponse res = DcaeRestClient.translateModelToBlueprint(validInput);
		Report.log(Status.INFO, "Blueprint result: " + res.getResponse());
		assertThat(res.getStatusCode()).isEqualTo(200);
		assertThat(res.getResponse()).isEqualTo(expectedOutput);
	}

	@Test
	public void invalidInputFailureTest() throws IOException {
		RestResponse res = DcaeRestClient.translateModelToBlueprint("{\"template\":\"aW52YWxpZCBUb3NjYQ==\"}");
		Report.log(Status.INFO, "Blueprint result: " + res.getResponse());
		assertThat(res.getStatusCode()).isEqualTo(500);
	}
}
